fix: remove configuration containers

diff --git a/docker-compose.yaml b/docker-compose.yaml
--- a/docker-compose.yaml
+++ b/docker-compose.yaml
@@ -72,48 +72,52 @@ services:
       retries: 30
       start_period: 10s
 
-  control-center:
-    image: confluentinc/cp-enterprise-control-center:7.3.0
-    networks:
-      - arithmetic
-    hostname: control-center
-    container_name: control-center
-    depends_on:
-      kafka:
-        condition: service_healthy
-    ports:
-      - "9021:9021"
-    environment:
-      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:29092'
-      CONTROL_CENTER_REPLICATION_FACTOR: 1
-      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
-      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
-      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
-      PORT: 9021
-    healthcheck:
-      test: nc -z localhost 9021 || exit 1
-      interval: 5s
-      timeout: 2s
-      retries: 20
-      start_period: 10s
+  # control-center:
+  #   image: confluentinc/cp-enterprise-control-center:7.3.0
+  #   networks:
+  #     - arithmetic
+  #   hostname: control-center
+  #   container_name: control-center
+  #   depends_on:
+  #     kafka:
+  #       condition: service_healthy
+  #   ports:
+  #     - "9021:9021"
+  #   environment:
+  #     CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:29092'
+  #     CONTROL_CENTER_REPLICATION_FACTOR: 1
+  #     CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
+  #     CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
+  #     CONFLUENT_METRICS_TOPIC_REPLICATION: 1
+  #     PORT: 9021
+  #   healthcheck:
+  #     test: nc -z localhost 9021 || exit 1
+  #     interval: 5s
+  #     timeout: 2s
+  #     retries: 20
+  #     start_period: 10s
 
-  configure-kafka:
-    platform: linux/amd64
-    networks:
-      - arithmetic
-    image: "confluentinc/cp-enterprise-kafka:6.1.0"
-    depends_on:
-      kafka: 
-        condition: service_healthy
-    entrypoint: [ '/bin/sh', '-c' ]
-    command: |
-      "
-      echo -e 'Creating kafka topics'
-      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic OPERATION_CALCULATED --replication-factor 1 --partitions 1
+  # configure-kafka:
+  #   platform: linux/amd64
+  #   networks:
+  #     - arithmetic
+  #   image: "confluentinc/cp-enterprise-kafka:6.1.0"
+  #   depends_on:
+  #     kafka: 
+  #       condition: service_healthy
+  #   entrypoint: [ '/bin/sh', '-c' ]
+  #   command: |
+  #     "
+  #     echo -e 'Creating kafka topics'
+  #     kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic OPERATION_CALCULATED --replication-factor 1 --partitions 1
 
-      echo -e 'Successfully created the following topics:'
-      kafka-topics --bootstrap-server kafka:29092 --list
-      "
+  #     echo -e 'Successfully created the following topics:'
+  #     kafka-topics --bootstrap-server kafka:29092 --list
+
+  #     echo -e 'Giving permissions for all users'
+  #     kafka-acls --authorizer-properties zookeeper.connect=zookeeper:2181 --add --allow-principal User:'*' --operation Read --topic '*'
+  #     kafka-acls --authorizer-properties zookeeper.connect=zookeeper:2181 --add --allow-principal User:'*' --operation Describe --group '*'
+  #     "
 
   arithmetic-calulator:
     build:
@@ -138,18 +142,18 @@ services:
       retries: 20
       start_period: 20s
 
-  run-migrations:
-    build:
-      context: .
-      dockerfile: Dockerfile.dev
-    networks:
-      - arithmetic
-    volumes:
-      - .:/app
-    depends_on:
-      db:
-        condition: service_healthy
-    command: npm run migration:run
+  # run-migrations:
+  #   build:
+  #     context: .
+  #     dockerfile: Dockerfile.dev
+  #   networks:
+  #     - arithmetic
+  #   volumes:
+  #     - .:/app
+  #   depends_on:
+  #     db:
+  #       condition: service_healthy
+  #   command: npm run migration:run
 
 networks:
   arithmetic:
