Feat/observability (#16)

diff --git a/docker-compose.yaml b/docker-compose.yaml
--- a/docker-compose.yaml
+++ b/docker-compose.yaml
@@ -2,6 +2,8 @@ version: "3"
 services:
   db:
     image: mysql:8.0
+    networks:
+      - arithmetic
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: arithmetic
@@ -19,6 +21,8 @@ services:
 
   zookeeper:
     platform: linux/amd64
+    networks:
+      - arithmetic
     image: "confluentinc/cp-zookeeper:6.1.0"
     volumes:
       - ./.docker/zookeper:/var/lib/zookeeper
@@ -38,6 +42,8 @@ services:
 
   kafka:
     platform: linux/amd64
+    networks:
+      - arithmetic
     image: "confluentinc/cp-enterprise-kafka:6.1.0"
     container_name: kafka
     depends_on:
@@ -66,51 +72,62 @@ services:
       retries: 30
       start_period: 10s
 
-  control-center:
-    image: confluentinc/cp-enterprise-control-center:7.3.0
-    hostname: control-center
-    container_name: control-center
-    depends_on:
-      kafka:
-        condition: service_healthy
-    ports:
-      - "9021:9021"
-    environment:
-      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:29092'
-      CONTROL_CENTER_REPLICATION_FACTOR: 1
-      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
-      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
-      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
-      PORT: 9021
-    healthcheck:
-      test: nc -z localhost 9021 || exit 1
-      interval: 5s
-      timeout: 2s
-      retries: 20
-      start_period: 10s
+  # control-center:
+  #   image: confluentinc/cp-enterprise-control-center:7.3.0
+  #   networks:
+  #     - arithmetic
+  #   hostname: control-center
+  #   container_name: control-center
+  #   depends_on:
+  #     kafka:
+  #       condition: service_healthy
+  #   ports:
+  #     - "9021:9021"
+  #   environment:
+  #     CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:29092'
+  #     CONTROL_CENTER_REPLICATION_FACTOR: 1
+  #     CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
+  #     CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
+  #     CONFLUENT_METRICS_TOPIC_REPLICATION: 1
+  #     PORT: 9021
+  #   healthcheck:
+  #     test: nc -z localhost 9021 || exit 1
+  #     interval: 5s
+  #     timeout: 2s
+  #     retries: 20
+  #     start_period: 10s
 
-  configure-kafka:
-    platform: linux/amd64
-    image: "confluentinc/cp-enterprise-kafka:6.1.0"
-    depends_on:
-      kafka: 
-        condition: service_healthy
-    entrypoint: [ '/bin/sh', '-c' ]
-    command: |
-      "
-      echo -e 'Creating kafka topics'
-      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic OPERATION_CALCULATED --replication-factor 1 --partitions 1
+  # configure-kafka:
+  #   platform: linux/amd64
+  #   networks:
+  #     - arithmetic
+  #   image: "confluentinc/cp-enterprise-kafka:6.1.0"
+  #   depends_on:
+  #     kafka: 
+  #       condition: service_healthy
+  #   entrypoint: [ '/bin/sh', '-c' ]
+  #   command: |
+  #     "
+  #     echo -e 'Creating kafka topics'
+  #     kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic OPERATION_CALCULATED --replication-factor 1 --partitions 1
 
-      echo -e 'Successfully created the following topics:'
-      kafka-topics --bootstrap-server kafka:29092 --list
-      "
+  #     echo -e 'Successfully created the following topics:'
+  #     kafka-topics --bootstrap-server kafka:29092 --list
+
+  #     echo -e 'Giving permissions for all users'
+  #     kafka-acls --authorizer-properties zookeeper.connect=zookeeper:2181 --add --allow-principal User:'*' --operation Read --topic '*'
+  #     kafka-acls --authorizer-properties zookeeper.connect=zookeeper:2181 --add --allow-principal User:'*' --operation Describe --group '*'
+  #     "
 
   arithmetic-calulator:
     build:
       context: .
       dockerfile: Dockerfile.dev
+    networks:
+      - arithmetic
     volumes:
       - .:/app
+      - /app/node_modules
     depends_on:
       db:
         condition: service_healthy
@@ -125,13 +142,20 @@ services:
       retries: 20
       start_period: 20s
 
-  run-migrations:
-    build:
-      context: .
-      dockerfile: Dockerfile.dev
-    volumes:
-      - .:/app
-    depends_on:
-      db:
-        condition: service_healthy
-    command: npm run migration:run
+  # run-migrations:
+  #   build:
+  #     context: .
+  #     dockerfile: Dockerfile.dev
+  #   networks:
+  #     - arithmetic
+  #   volumes:
+  #     - .:/app
+  #   depends_on:
+  #     db:
+  #       condition: service_healthy
+  #   command: npm run migration:run
+
+networks:
+  arithmetic:
+    name: arithmetic
+    driver: bridge
